
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;
	
	private global::GMap.NET.GtkSharp.GMapControl MainMap;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.MainMap = new global::GMap.NET.GtkSharp.GMapControl ();
		this.MainMap.Name = "MainMap";
		this.MainMap.MaxZoom = 0;
		this.MainMap.MinZoom = 0;
		this.MainMap.MouseWheelZoomEnabled = true;
		this.MainMap.ShowTileGridLines = false;
		this.MainMap.GrayScaleMode = false;
		this.MainMap.NegativeMode = false;
		this.MainMap.Bearing = 0F;
		this.MainMap.Zoom = 0;
		this.MainMap.RoutesEnabled = false;
		this.MainMap.PolygonsEnabled = false;
		this.MainMap.MarkersEnabled = false;
		this.MainMap.CanDragMap = true;
		this.hbox1.Add (this.MainMap);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.MainMap]));
		w1.Position = 0;
		this.Add (this.hbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
